pipeline {
    agent any

    triggers {
        GenericTrigger(
         genericVariables: [
          [key: 'ref', value: '$.ref']
         ],
         causeString: 'Triggered on $ref',
         token: 'myToken12345678',
         tokenCredentialId: '',
         printContributedVariables: true,
         printPostContent: true,
         silentResponse: false,
         shouldNotFlatten: false,
         regexpFilterText: '$ref',
         regexpFilterExpression: '^(refs/heads/development)\$'
        )
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World from self-hosted Jenkins'
                echo "This is a test project for development branch"
            }
        }
        stage('clone repo') {
            steps {
                git branch: "development", url: 'https://github.com/mahadihassanrazib/full-stack-crud-project-with-react-node-mysql.git'

                script {
                    sh "ls -lah"
                    sh "echo branch is: development"
                }
            }
        }
    }
}
